### ISSUE TITLE
missing project (.xpr) file

### ISSUE THREAD

**Issue by leardilap** [odelayIO/KR260-HLS-Fixed-Gain-Stream#9]
Hi, thanks for your repo, I wanted to tried it out but it fails because there is no project file added to the repo.
Thanks!

**Comment by odelayIO** [comment]
Sorry for the delay in the response.

The project file (.xpr) will be created by the Makefile (see instruction in the README file at base of repo).  The instructions utilize the Xilinx Vivado 2022.1 Docker container.  I have included the startup script for the Xilinx Vivado Docker container.  Instructions how to create the Xilinx Vivado 2022.1 Docker image can be found in https://github.com/odelayIO/vivado2022.1_docker repo.

When the project if finished building, then you can type "make start_gui" on the command line inside the Xilinx Docker container.  This will open the project in Xilinx Vivado GUI.
